### PR TITLE
Temp pub cache dir + cleanup. Fixes #282.

### LINKED ISSUE #282: analyzer service: Running out of disk space
Error:
    Problem running proc: exit code - 1&lt;***&gt;MSG : Downloading angel_framework 1.0.8...&lt;***&gt;FINE: Pub 1.25.0-dev.9.0
    IO  : Get versions from https://pub.dartlang.org/api/packages/angel_framework.
    IO  : HTTP GET https://pub.dartlang.org/api/packages/angel_framework
        | Accept: application/vnd.pub.v2+json
        | X-Pub-OS: linux
        | X-Pub-Command: cache add
        | X-Pub-Session-ID: 7F9C8F61-B1DF-4D2A-B4AA-9A1BF87576F4
        | X-Pub-Environment: bot.pub_dartlang_org.docker:bot.pkg_pana
        | user-agent: Dart pub 1.25.0-dev.9.0
    IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/angel_framework
        | took 0:00:00.176389
        | date: Thu, 03 Aug 2017 17:52:24 GMT
        | transfer-encoding: chunked
        | via: 1.1 google
        | content-type: application/json
        | x-frame-options: SAMEORIGIN
        | x-xss-protection: 1; mode=block
        | x-content-type-options: nosniff
        | server: nginx
    IO  : Get package from https://pub.dartlang.org/packages/angel_framework/versions/1.0.8.tar.gz.
    ERR : Creation of temporary directory failed, path = '/root/.pub-cache/_temp/dir' (OS Error: No space left on device, errno = 28)
    FINE: Exception type: FileSystemException
    FINE: dart:io                                                                     _Directory.createTempSync
        | package:pub/src/io.dart 255                                                 createTempDir
        | package:pub/src/system_cache.dart 117                                       SystemCache.createTempDir
        | package:pub/src/source/hosted.dart 299                                      BoundHostedSource._download
        | package:pub/src/source/hosted.dart 195                                      BoundHostedSource.downloadToSystemCache
        | package:pub/src/command/cache_add.dart 75                                   CacheAddCommand.run.downloadVersion
        | package:pub/src/command/cache_add.dart 85                                   CacheAddCommand.run
        | package:args/command_runner.dart 194                                        CommandRunner.runCommand
        | package:pub/src/command_runner.dart 168                                     PubCommandRunner.runCommand.&lt;fn&gt;
        | dart:async                                                                  new Future.sync
        | package:pub/src/utils.dart 102                                              captureErrors.&lt;fn&gt;
        | package:stack_trace                                                         Chain.capture
        | package:pub/src/utils.dart 117                                              captureErrors
        | package:pub/src/command_runner.dart 168                                     PubCommandRunner.runCommand
        | package:pub/src/command_runner.dart 117                                     PubCommandRunner.run
        | /tmp/tmpodI7sK/dart-1.25.0-dev.9.0/dart/third_party/pkg/pub/bin/pub.dart 8  main
        | ===== asynchronous gap ===========================
        | dart:async                                                                  _Completer.completeError
        | package:pub/src/source/hosted.dart 311                                      BoundHostedSource._download
        | ===== asynchronous gap ===========================
        | dart:async                                                                  new Future.microtask
        | package:pub/src/source/hosted.dart 293                                      BoundHostedSource._download
        | package:pub/src/source/hosted.dart 195                                      BoundHostedSource.downloadToSystemCache
        | ===== asynchronous gap ===========================
        | dart:async                                                                  new Future.microtask
        | package:pub/src/source/hosted.dart 190                                      BoundHostedSource.downloadToSystemCache
        | package:pub/src/command/cache_add.dart 75                                   CacheAddCommand.run.downloadVersion
        | ===== asynchronous gap ===========================
        | dart:async                                                                  new Future.microtask
        | package:pub/src/command/cache_add.dart 66                                   CacheAddCommand.run.downloadVersion
        | package:pub/src/command/cache_add.dart 85                                   CacheAddCommand.run
        | ===== asynchronous gap ===========================
        | dart:async                                                                  _asyncThenWrapperHelper
        | package:pub/src/command/cache_add.dart 28                                   CacheAddCommand.run
        | package:args/command_runner.dart 194                                        CommandRunner.runCommand
        | ===== asynchronous gap ===========================
        | dart:async                                                                  new Future.microtask
        | package:args/command_runner.dart 142                                        CommandRunner.runCommand
        | package:pub/src/command_runner.dart 168                                     PubCommandRunner.runCommand.&lt;fn&gt;
        | dart:async                                                                  new Future.sync
        | package:pub/src/utils.dart 102                                              captureErrors.&lt;fn&gt;
        | package:stack_trace                                                         Chain.capture
        | package:pub/src/utils.dart 117                                              captureErrors
        | package:pub/src/command_runner.dart 168                                     PubCommandRunner.runCommand

Stack:
    #0      handleProcessErrors (package:pana/src/utils.dart:98:5)
    #1      PubEnvironment.getLocation (package:pana/src/sdk_env.dart:181:18)
    &lt;asynchronous suspension&gt;
    #2      PackageAnalyzer.inspectPackage (package:pana/pana.dart:63:23)
    &lt;asynchronous suspension&gt;
    #3      PanaRunner.runTask (package:pub_dartlang_org/analyzer/pana_runner.dart:34:32)
    &lt;asynchronous suspension&gt;
    #4      TaskScheduler.run (package:pub_dartlang_org/shared/task_scheduler.dart:44:25)
    &lt;asynchronous suspension&gt;
    #5      _runScheduler.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///project/app/bin/service/analyzer.dart:83:10)
    &lt;asynchronous suspension&gt;
    #6      withCorrectDatastore (package:pub_dartlang_org/shared/service_utils.dart:39:15)
    #7      _runScheduler.&lt;anonymous closure&gt; (file:///project/app/bin/service/analyzer.dart:76:11)
    &lt;asynchronous suspension&gt;
    #8      withAppEngineServices.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:43:51)
    #9      _withAppEngineServicesInternal.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:112:20)
    &lt;asynchronous suspension&gt;
    #10     _ServiceScope._fork.&lt;anonymous closure&gt; (package:gcloud/service_scope.dart:207:19)
    #11     _rootRun (dart:async/zone.dart:1120)
    #12     _CustomZone.run (dart:async/zone.dart:1001)
    #13     runZoned (dart:async/zone.dart:1467)
    #14     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #15     fork (package:gcloud/service_scope.dart:103:30)
    #16     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:102:10)
    #17     withAppEngineServices (package:appengine/src/appengine_internal.dart:43:5)
    #18     withAppEngineServices (package:appengine/appengine.dart:108:10)
    #19     _runScheduler (file:///project/app/bin/service/analyzer.dart:75:3)
    #20     _startIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:268)
    #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)</logs-summary>

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

File: app/lib/analyzer/pana_runner.dart [hunk 1]
```diff
@@ -40,6 +46,10 @@ class PanaRunner {
       _logger.severe('Pana execution failed.', e, st);
     }
 
+    if (tempDir != null) {
+      await tempDir.delete(recursive: true);
```
Comment (kevmoo) [inline app/lib/analyzer/pana_runner.dart]: Put this in `finally` in the above try block?
