### PR TITLE
Minimal URI validation.

### LINKED ISSUE #1716: Invalid argument(s): Illegal percent encoding in URI
This throws an error in our logs. However, it's a user error (HTTP 400) rather than our error and shouldn't be logged as an error.

```
pub: Handling request: https://pub.dartlang.org/packages/shelf_web_socket%E5%B0%86%E6%AD%A4%E7%A4%BA%E4%BE%8B%E5%AF%BC%E5%85%A5%E2%80%8B%E2%80%8B'package%EF%BC%9Ashelf

pub: Request handler failed

Error:
    Invalid argument(s): Illegal percent encoding in URI

Stack:
    dart:core/uri.dart 2835:11                                    _Uri._uriDecode
    dart:core/uri.dart 1109:17                                    Uri.decodeComponent
    package:pub_dartlang_org/frontend/handlers.dart 427:54        _packageHandler
    package:pub_dartlang_org/frontend/handlers.dart 102:18        appHandler
    bin/service/frontend.dart 59:36                               _main.<fn>.<fn>
...
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes #1716

### CODE REVIEW

File: app/lib/shared/handler_helpers.dart [hunk 1]
```diff
@@ -72,6 +73,27 @@ Request ID: ${context.traceId}
...
+    }
+  };
+}
+
+bool _isValidUri(shelf.Request request) {
+  final uri = request.requestedUri;
+  try {
+    // should be able to parse path segments
+    uri.pathSegments.forEach(Uri.decodeComponent);
+  } catch (_) {
```
Comment (sortie) [inline app/lib/shared/handler_helpers.dart]: Can an exact Exception be caught?
