### PR TITLE
Handle search query parsing gracefully.

### LINKED ISSUE #1970: Exception on weird URLs.
This is coming from Jan 14:

````
Handling request: https://pub.dartlang.org/flutter/packages?q=1&api=0&sort=%27-function()%7Bxssdetected(10911)%7D()-%22%3E%5C%22%3E%3CscrIpt%3Exssdetected(10911)%3C/scrIpt%3E%3CaUdio%20src%3Dx%20oNerror%3Dxssdetected(10911)%3E%3C%22-%27-function()%7Bxssdetected(10911)%7D()

pub: Request handler failed

Error:
    Exception: Unable to parse SearchOrder: '-function(){xssdetected(10911)}()-">\"><scrIpt>xssdetected(10911)</scrIpt><aUdio src=x oNerror=xssdetected(10911)><"-'-function(){xssdetected(10911)}()

Stack:
    package:pub_dartlang_org/shared/search_service.dart 195:3     parseSearchOrder
    package:pub_dartlang_org/shared/search_service.dart 559:9     parseFrontendSearchQuery
    package:pub_dartlang_org/frontend/handlers.dart 316:23        _packagesHandlerHtmlCore
    package:pub_dartlang_org/frontend/handlers.dart 302:5         _flutterPackagesHandlerHtml
````
We should handle this silently.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #1970

### CODE REVIEW

File: app/lib/frontend/handlers/custom_api.dart [hunk 1]
```diff
@@ -225,7 +229,13 @@ Future<shelf.Response> apiHistoryHandler(shelf.Request request) async {
 
 /// Handles requests for /api/search
 Future<shelf.Response> apiSearchHandler(shelf.Request request) async {
-  final searchQuery = parseFrontendSearchQuery(request.requestedUri, null);
+  SearchQuery searchQuery;
+  try {
+    searchQuery = parseFrontendSearchQuery(request.requestedUri, null);
+  } catch (e, st) {
```
Comment (sigurdm) [inline app/lib/frontend/handlers/custom_api.dart]: * Should we narrow to specific errors?
The catch-all might hide bugs in our parsing code.

* It seems there is a potential to have a `parseFrontendSearchQueryLoggingErrors` function.

**Comment by isoos** [comment]
PTAL. I think the logging idea should be extended a bit, and separated from this one, because catching exceptions is only a subset of the error space. E.g. if our parsing ignores a parameter that is sent by the client, it doesn't throw an exception, yet it may be an error.
